version: '3'
services:
  web:
    image: vue-express-mongo-site
    build: .
    command: npm run docker-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"

  mongo:
    image: mongo:4.4
    ports: 
      - 27017:27017
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=password
    stdin_open: true
