version: '3'
services:
  web:
    image: vue-express-mongo-site
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

  mongo:
    image: mongo:4.4
    ports: 
      - 27017:27017
    env_file: ./.env
    environment:
      - MONGO-INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO-INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGODB_URI=$MONGODB_URI
    stdin_open: true
